config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'users', to: 'reloads#user_edit'
  get 'users/password_update', to: 'reloads#user_password_edit'
  resource :users, only: [:edit, :update, :destroy] do
    member do
      post :test_login
      get :password_edit
      patch :password_update
      get :search
      get :favorite_recipes
      get :friends
    end
  end
  resources :users, only: [:show]

  resource :relationships, only: [:create, :update, :destroy]
  resource :bookmarks, only: [:create, :destroy]
  resource :meals, only: [:index, :show]
  resource :menus, only: [:create, :destroy]
  
  get 'recipes/:id/easy_update', to: 'reloads#recipe_show'
  get 'recipes', to: 'reloads#recipe_new'
  get 'recipes/easy_create', to: 'reloads#recipe_new'
  get 'recipes/:id/ingredients', to: 'reloads#ingredients_edit'
  get 'recipes/:id/steps', to: 'reloads#steps_edit'
  resource :recipes, only: [:new, :create] do
    collection do
      post :easy_create
      get :sort
      get :keyword_search
      get :feature_search
    end
  end
  resources :recipes, only: [:show,  :edit, :update, :destroy] do
    member do
      patch :easy_update
      patch :size_update
      patch :publish
      patch :stop_publish
    end
    resource :ingredients, :steps, only: [:edit, :update]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :image, ImageUploader

  # レシピのタイトル、説明文必須
  validates :title, presence: true, length: { maximum: 20 }, lt4bytes: true
  validates :explanation, presence: true, length: { maximum: 60 }, lt4bytes: true
  validates :size, length: { maximum: 10 }
  validates :homepage, url: { allow_blank: true }
  validates :status, presence: true

  # statusカラム設定
  enum status: { draft: 0, published: 1 }

  belongs_to :user
  has_one :feature, dependent: :destroy
  accepts_nested_attributes_for :feature
  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :menus, dependent: :destroy

  scope :recent, -> { order(created_at: :desc) }

  # レシピの変更後属性を割り当て
  def replace_attributes(recipe_params)
    assign_attributes(recipe_params.except(:remove_img))
    remove_image! if recipe_params[:remove_img] == '1'
  end

  # レシピの公開、非公開
  def publishing
    update(status: 1)
  end

  def drafting
    update(status: 0)
  end

  def draft?
    status == 'draft'
  end

  # レシピをお気に入りの多い順に並べ替え
  def self.sort_likes
    Recipe.recent.includes(:bookmarks).sort { |a, b| b.bookmarks.size <=> a.bookmarks.size }
  end

  # レシピキーワード検索
  def self.keyword_search(search)
    keywords = search.split(/[[:blank:]]+/)
    if keywords.empty?
      false
    else
      recipes = Recipe
      keywords.each do |keyword|
        recipes = recipes.where(['title LIKE ? OR explanation LIKE ?', "%#{keyword}%", "%#{keyword}%"])
      end
      recipes
    end
  end

  # レシピ特徴検索
  def self.feature_search(search)
    requirement = search.select! { |_k, v| v.present? }
    features = Feature.where(requirement)
    id_list = features.pluck(:recipe_id)
    Recipe.where(id: id_list)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include Common
  before_action :require_user_logged_in
  before_action :prepare_search, except: %i[sort keyword_search feature_search]
  before_action :prepare_meals
  before_action -> { accessable_recipe_check(params[:id]) }, only: %i[show]
  before_action -> { user_author_match(params[:id]) },
                only: %i[edit update easy_update size_update destroy publish stop_publish]

  def show; end

  def new
    @recipe = current_user.recipes.build
    @recipe.build_feature
  end

  def create
    @recipe = current_user.recipes.build(recipe_params.except(:remove_img))
    if @recipe.save
      redirect_to edit_recipe_ingredients_url(@recipe)
    else
      render :new
    end
  end

  def easy_create
    @recipe = current_user.recipes.build(recipe_params.except(:remove_img))
    if @recipe.save
      redirect_to recipe_url(@recipe)
    else
      render :new
    end
  end

  def edit; end

  def update
    @recipe.replace_attributes(recipe_params)
    if @recipe.save
      redirect_to edit_recipe_ingredients_url(@recipe)
    else
      render :edit
    end
  end

  def easy_update
    @recipe.replace_attributes(recipe_params)
    if @recipe.save
      redirect_to recipe_url(@recipe)
    else
      render :edit
    end
  end

  def size_update
    @status = @recipe.update(size_params) ? 'success' : 'fail'
  end

  def destroy
    @recipe.destroy
    flash[:success] = 'レシピが削除されました'
    redirect_to root_url
  end

  def publish
    @recipe.publishing
    redirect_to recipe_url(@recipe)
  end

  def stop_publish
    @recipe.drafting
    redirect_to recipe_url(@recipe)
  end

  def sort
    session[:sort] = params[:sort_order]
    redirect_back(fallback_location: root_path)
  end

  def keyword_search
    recipes = current_user.accessable_recipes.keyword_search(params[:search])
    if recipes
      recipe_search_common(recipes)
      @search_feature = {}
      @search_keyword = session[:keyword] = params[:search]
    else
      redirect_to root_url
    end
  end


  def feature_search
    @search_feature = feature_params
    if session[:keyword].present?
      @search_keyword = session[:keyword]
      pre_recipes = current_user.accessable_recipes.keyword_search(@search_keyword)
      recipes = pre_recipes.feature_search(@search_feature)
    else
      recipes = current_user.accessable_recipes.feature_search(@search_feature)
    end
    recipe_search_common(recipes)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :image, :remove_img, :explanation, :homepage,
                                   feature_attributes: %i[id amount dish_type cooking_method main_food])
  end

  def feature_params
    params.permit(:amount, :dish_type, :main_food, :cooking_method)
  end

  def size_params
    params.permit(:size)
  end
end

app/views/recipes/_publish_button.html.erb
<!--レシピ公開ボタン-->
<%= link_to "→レシピを友だちに公開する", publish_recipe_path(recipe), 
                                        method: :patch, 
                                        data: { confirm: '本当に公開してよろしいですか？' }, 
                                        class: 'button' %>

app/views/recipes/_recipe_form.html.erb
<div class="card">
  <div class="card-body p-4">
    <%= form_with(model: recipe, local: true, authenticity_token: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-row">
        <div class="col-sm-5 pr-3">
          <div class="form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :image, "画像" %>
            <div class="mb-3">
              <%= cl_image_tag(@recipe.image.to_s, alt: "レシピ画像", id: :img_prev) %>
            </div>
            <%= f.file_field :image, class: "image", id: "book_img" %>      
          </div>
        </div>
        <div class="col-sm-7 pl-3">
          <div class="form-group">
            <%= f.label :explanation, "説明" %>
            <%= f.text_area :explanation, class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :homepage, "参考URL" %>
            <%= f.text_field :homepage, class: 'form-control'%>
          </div>
        </div>
      </div>
      <div class="form-row border-top py-3">
        <%= f.fields_for :feature do |s| %>
          <div class="col-sm-3">
            <div class="form-group">
              <%= s.label :amount, "ボリュームは？" %>
              <%= s.select :amount,
                  Feature.amounts.keys.map {|k| [I18n.t("enums.feature.amount.#{k}"), k]},
                  { include_blank: '選択してください'},
                  class: 'form-control' %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= s.label :dish_type, "何系料理？" %>
              <%= s.select :dish_type,
                  Feature.dish_types.keys.map {|k| [I18n.t("enums.feature.dish_type.#{k}"), k]},
                  { include_blank: '選択してください'},
                  class: 'form-control' %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= s.label :main_food, "メインの食材は？" %>
              <%= s.select :main_food,
                  Feature.main_foods.keys.map {|k| [I18n.t("enums.feature.main_food.#{k}"), k]},
                  { include_blank: '選択してください'},
                  class: 'form-control' %>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="form-group">
              <%= s.label :cooking_method, "調理法は？" %>
              <%= s.select :cooking_method,
                  Feature.cooking_methods.keys.map {|k| [I18n.t("enums.feature.cooking_method.#{k}"), k]},
                  { include_blank: '選択してください'},
                  class: 'form-control' %>
            </div>
          </div>
        <% end %>
      </div>
        <div class="col-sm-6 offset-sm-3">
          <%= f.submit '完了する', formaction: easy_path, class: 'btn btn-sm submit-btn btn-block' %>
          <%= f.submit '保存して材料入力に進む',　name: "", class: 'btn btn-sm submit-btn btn-block' %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        </div>
    <% end %>
  </div>
</div>

app/views/recipes/_recipe_lower.html.erb
<% if recipe.steps.present? %>
  <div class="row">
    <div class="col-sm-4">
      <h2>作り方</h2>
    </div>
  </div>
  <div class="row">
    <% recipe.steps.each do |step| %>
      <div class="col-sm-3">
        <h2 class="mb-1"><%= step.number %></h2>
        <p><%= step.content %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/_recipe_upper.html.erb
<div class="mt-2">
  <h1><%= recipe.title %></h1>
</div>
<div class="row mb-4">
  <div class="col-sm-5">
    <div class="img-square">
      <% if recipe.image.present? %>
        <%= cl_image_tag(recipe.image.to_s, alt: recipe.title) %>
      <% elsif homepage_image(recipe) %>
        <%= image_tag(homepage_image(recipe), alt: homepage_title(recipe)) %>
      <% else %>
        <%= cl_image_tag(recipe.image.to_s, alt: recipe.title) %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-7">
    <h3><%= recipe.explanation %></h3>
    <div class="d-flex justify-content-end"> 
      <%= link_to "by #{recipe.user.name}", user_path(recipe.user), class: "font-orange font-sm" %>
    </div>
    <% if recipe.homepage.present? %>
      <div class="font-sm mt-4">
        <h2 class="border-gray pb-1">参考ホームページ</h2>
        <h5><%= link_to homepage_title(recipe), recipe.homepage, target: :_blank, class: "font-orange" %></h5>
      </div>
    <% end %>
    <% if @recipe.ingredients.present? %>
      <div class="mt-4">
        <div class="border-gray pb-1">
          <h2 class="d-inline">材料</h2>
          <% if recipe.size.present? %>
            <h4 class="d-inline">(<%= recipe.size %>)</h4>
          <% end %>
        </div>
        <table class="table table-sm table-striped table-borderless font-sm">
          <% @recipe.ingredients.each do |ingredient| %>
            <tr><td><%= ingredient.name %></td><td><div class="text-right"><%= ingredient.quantity %></div></td></tr>
          <% end %>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_recipes.html.erb
<div class="row m-0">
  <% recipes.each do |recipe| %>
    <div class="col-sm-3 col-6 px-2 pt-0 pb-3">
      <a href="/recipes/<%= recipe.id %>" class="card border-0">
        <div class="img-square">
          <% if recipe.image.present? %>
            <%= cl_image_tag(recipe.image.to_s, class: "card-img-top rounded-0", alt: recipe.title) %>
          <% elsif homepage_image(recipe) %>
            <%= image_tag(homepage_image(recipe), class: "card-img-top rounded-0", alt: homepage_title(recipe)) %>
          <% else %>
            <%= cl_image_tag(recipe.image.to_s, class: "card-img-top rounded-0", alt: recipe.title) %>
          <% end %>
        </div>
        <div class="card-img-overlay p-1">
          <h2 class="fa-2x">      
            <span class="fa-layers fa-fw">
              <i class="fas fa-heart"></i>
              <span class="fa-layers-text fa-inverse" data-fa-transform="shrink-10"><%= recipe.bookmarks.count %></span>
            </span>
          </h2>
        </div>
        <div class="card-img-overlay text-right p-1">
          <% if recipe.draft? %>
            <h4><span class="badge badge-light">非公開</span></h4>
          <% end %>
          </div>
        <div class="card-footer border-0 bg-white px-0 py-1">
          <h4 class="my-1 font-orange"><%= recipe.title %></h4>
          <h4 class="mt-1">by <%= recipe.user.name %></h4>
        </div>
      </a>
    </div>
  <% end %>
</div>

app/views/recipes/_search.html.erb
<div class="col-md-3 px-2 mb-3">
  <div class="card p-2 rouded-0 border-0 bg_skew_dot">
    <div class="card border-0">
      <div class="card-header search-header p-1 border-0 rounded-0">
        <div class="d-flex justify-content-center">
          <h4 class="mb-0 text-white d-inline pt-1"><i class="fas fa-search"></i> レシピを探す</h4>
          <a class="btn btn-small button p-0 ml-2 text-white d-inline d-md-none"
              data-toggle="collapse"
              href="#recipe-search"
              role="button"
              aria-expand="false"
              aria-controls="recipe-search"><i class="fas fa-angle-down"></i>
          </a>
        </div>
      </div>
      <div class="card-body p-0">
        <div class="collapse d-md-none" id="recipe-search">
          <%= render 'recipes/search_parts', keyword: keyword, feature: feature, keyword_submit: keyword_submit, feature_submit: feature_submit %>
        </div>
        <div class="d-none d-md-block">
          <%= render 'recipes/search_parts', keyword: keyword, feature: feature, keyword_submit: keyword_submit, feature_submit: feature_submit %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_search_parts.html.erb
<div class="p-3">
  <h3 class="mb-3 mt-0">キーワードで検索</h3>
  <%= form_with(url: keyword_search_recipes_path, method: :get, local: true) do |f| %>
    <div class="form-row">
      <div class="col-md-12 col-12 mb-3">
        <%= f.text_field :search, value: keyword,  class: 'form-control form-control-sm search-box' %>
      </div>
      <div class="col-md-3 offset-md-9 d-flex justify-content-end">
        <%= f.submit keyword_submit, class: 'btn btn-sm search-btn' %>
      </div>
    </div>
  <% end %>
  <h3 class="my-3">特徴で検索</h3>
  <div class="row">
    <div class="col-md-12">
      <!--特徴検索フォーム-->
      <%= form_with(url: feature_search_recipes_path, method: :get, local: true) do |f| %>
        <div class="form-row">
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :amount, "ボリュームは？", class: 'font-weight-bold' %>
              <%= f.select :amount,
                  Feature.amounts.keys.map {|k| [I18n.t("enums.feature.amount.#{k}"), k]},
                  { include_blank: '指定しない', selected: feature[:amount] },
                  class: 'form-control form-control-sm search-box' %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :dish_type, "何系料理？", class: 'font-weight-bold' %>
              <%= f.select :dish_type,
                  Feature.dish_types.keys.map {|k| [I18n.t("enums.feature.dish_type.#{k}"), k]},
                  { include_blank: '指定しない', selected: feature[:dish_type]},
                  class: 'form-control form-control-sm search-box' %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :main_food, "メインの食材は？", class: 'font-weight-bold' %>
              <%= f.select :main_food,
                  Feature.main_foods.keys.map {|k| [I18n.t("enums.feature.main_food.#{k}"), k]},
                  { include_blank: '指定しない', selected: feature[:main_food]},
                  class: 'form-control form-control-sm search-box' %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <%= f.label :cooking_method, "調理法は？", class: 'font-weight-bold' %>
              <%= f.select :cooking_method,
                  Feature.cooking_methods.keys.map {|k| [I18n.t("enums.feature.cooking_method.#{k}"), k]},
                  { include_blank: '指定しない', selected: feature[:cooking_method]},
                  class: 'form-control form-control-sm search-box' %>
            </div>
          </div>
          <div class="col-md-3 offset-md-9 d-flex justify-content-end">
            <%= f.submit feature_submit, class: 'btn btn-sm search-btn' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_set_size_button.html.erb
<button type="button" class="btn button px-0" data-toggle="modal" data-target="#size-modal" data-backdrop="static">
  ＜何人分のレシピか登録する＞</button>
<div class="modal fade" id="size-modal" tabindex="-1"
      role="dialog" aria-labelledby="label1" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label1">このレシピは何人分ですか？ (例 2人分)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with(url: size_update_recipe_path(recipe), method: :patch) do |f| %>
        <div class="modal-body">
          <!--エラーメッセージ-->
          <div id="size-validation-error"></div>
          <div class="form-group">
            <%= f.text_field :size, class: 'form-control', value: recipe.size %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">キャンセル</button>
          <%= f.submit '登録',　name: "", class: 'btn btn-sm submit-btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_stop_publish_button.html.erb
<!--公開停止ボタン-->
<%= link_to "非公開にする", stop_publish_recipe_path(recipe), 
                            method: :patch,
                            data: { confirm: 'レシピを非公開にしてよろしいですか？' },
                            class: 'button pr-2 border-right' %>

app/views/recipes/edit.html.erb
<% content_for(:html_title) { "#{@recipe.title}のレシピ概要入力 | Wagakon" } %>
<% breadcrumb :recipe_edit, @recipe %>
<%= render "layouts/breadcrumbs" %>
<%= render "layouts/side_bar" do %>    
  <div class="card p-md-2 mx-2">
    <div class="card-body px-2 py-3">
      <h2 class="heading">レシピ概要を入力する</h2>
      <%= render 'recipes/form', recipe: @recipe, path: recipe_path, easy_path: easy_update_recipe_path do |f| %>
        <div class="form-check mb-2">
          <%= f.check_box :remove_img, class: "form-check-input", type: "checkbox", checked_value: "1", unchecked_value: "0", id: "defaultCheck1" %>
          <%= f.label :remove_img, "画像を削除する", class: "form-check-label", for: "defaultCheck1" %>
        </div>          
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/feature_search.html.erb
<% content_for(:html_title) { "レシピ検索結果一覧 | Wagakon" } %>
<%= render "layouts/side_bar" do %>    
  <div class="row m-0">
    <div class="col-md-12 px-2">
      <div class="bg-gray px-3 py-2 mb-2 mx-0">
        <h4 class="m-0">検索結果：<%= @count %>件</h4>
      </div>
      <!--レシピ並べ替え-->
      <%= render 'recipes/sort_list', path: sort_recipes_path %>
    </div> 
  </div>
  <% if @recipes.empty? %>
    <h3 class="pl-2">条件に一致するレシピがありません</h3>
  <% else %>
    <%= render 'recipes/index', recipes: @recipes %>
  <% end %>
<% end %>

app/views/recipes/keyword_search.html.erb
<% content_for(:html_title) { "レシピ検索結果一覧 | Wagakon" } %>
<%= render "layouts/side_bar" do %>    
  <div class="row m-0">
    <div class="col-md-12 px-2">
      <div class="bg-gray px-3 py-2 mb-2 mx-0">
        <h4 class="m-0">検索結果：<%= @count %>件</h4>
      </div>
      <!--レシピ並べ替え-->
      <%= render 'recipes/sort_list', path: sort_recipes_path %>
    </div> 
  </div>
  <% if @recipes.empty? %>
    <h3 class="pl-2">キーワードに一致するレシピがありません</h3>
  <% else %>
    <%= render 'recipes/index', recipes: @recipes %>
  <% end %>
<% end %>

app/views/recipes/new.html.erb
<% content_for(:html_title) { "新規レシピ作成 | Wagakon" } %>
<% breadcrumb :recipe_new %>
<%= render "layouts/breadcrumbs" %>
<%= render "layouts/side_bar" do %>    
  <div class="card p-md-2 mx-2">
    <div class="card-body px-2 py-3">
      <h2 class="heading">レシピ概要を入力する</h2>
      <%= render 'recipes/form', recipe: @recipe, path: recipes_path, easy_path: easy_create_recipes_path %>
    </div>
  </div>
<% end %>

app/views/recipes/search.html.erb
<h2>検索結果：<%= @recipes.count %>件</h2>
<% if @recipes.empty? %>
  <div class="alert alert-warning">キーワードに一致するレシピがありません</div>
<% else %>
  <%= render 'recipes/recipes', recipes: @recipes %>
<% end %>