config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'users', to: 'reloads#user_edit'
  get 'users/password_update', to: 'reloads#user_password_edit'
  resource :users, only: [:edit, :update, :destroy] do
    member do
      post :test_login
      get :password_edit
      patch :password_update
      get :search
      get :favorite_recipes
      get :friends
    end
  end
  resources :users, only: [:show]

  resource :relationships, only: [:create, :update, :destroy]
  resource :bookmarks, only: [:create, :destroy]
  resource :meals, only: [:index, :show]
  resource :menus, only: [:create, :destroy]
  
  get 'recipes/:id/easy_update', to: 'reloads#recipe_show'
  get 'recipes', to: 'reloads#recipe_new'
  get 'recipes/easy_create', to: 'reloads#recipe_new'
  get 'recipes/:id/ingredients', to: 'reloads#ingredients_edit'
  get 'recipes/:id/steps', to: 'reloads#steps_edit'
  resource :recipes, only: [:new, :create] do
    collection do
      post :easy_create
      get :sort
      get :keyword_search
      get :feature_search
    end
  end
  resources :recipes, only: [:show,  :edit, :update, :destroy] do
    member do
      patch :easy_update
      patch :size_update
      patch :publish
      patch :stop_publish
    end
    resource :ingredients, :steps, only: [:edit, :update]
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  validates :status, presence: true
  validates :user_id, presence: true, uniqueness: { scope: :friend_id }

  # statusカラム設定
  enum status: { requesting: 0, receiving: 1, approved: 2 }

  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_friend

  def create
    current_user.friend_request(@friend)
    redirect_to friends_users_url
  end

  def update
    current_user.friend_approve(@friend)
    redirect_to friends_users_url
  end

  def destroy
    current_user.friend_delete(@friend)
    redirect_to friends_users_url
  end

  private

  def set_friend
    @friend = User.find(params[:user_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  def requesting_friend?(user, friend)
    user.requesting_friends.include?(friend)
  end

  def receiving_friend?(user, friend)
    user.receiving_friends.include?(friend)
  end

  def approved_friend?(user, friend)
    user.approved_friends.include?(friend)
  end
end

app/views/relationships/_add_friend_button.html.erb
<% if requesting_friend?(current_user, user) %>
  <h3>友だちリクエスト中のユーザーです。</h3>
<% elsif receiving_friend?(current_user, user) %>
  <h3>友だちリクエスト受信中のユーザーです。</h3>
<% elsif approved_friend?(current_user, user) %>
  <h3>友だちに追加済みユーザーです。</h3>
<% elsif current_user == user %>
  <h3>自身を友だちに追加することはできません。</h3>
<% else %>
  <%= form_with(url: relationships_path, local: true) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit '友だちリクエストを送る', class: 'btn btn-sm button' %>
  <% end %>
<% end %>

app/views/relationships/_add_friends_button.html.erb
<% if current_user.requesting_friend?(user) %>
  <h3>友だちリクエスト中のユーザーです。</h3>
<% elsif current_user.receiving_friend?(user) %>
  <h3>友だちリクエスト受信中のユーザーです。</h3>
<% elsif current_user.approved_friend?(user) %>
  <h3>友だちに追加済みユーザーです。</h3>
<% elsif current_user == user %>
  <h3>自身を友だちに追加することはできません。</h3>
<% else %>
  <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit '友だちリクエストを送る', class: 'btn btn-sm btn-outline-secondary' %>
  <% end %>
<% end %>

app/views/relationships/_approve_friend_button.html.erb
<%= form_with(url: relationships_path, method: :patch) do |f| %>
  <%= hidden_field_tag :user_id, friend.id %>
  <%= f.submit "承認", class: 'btn btn-sm button header-btn mr-1 p-0' %>
<% end %>

app/views/relationships/_delete_friend_button.html.erb
<%= form_with(url: relationships_path, method: :delete) do |f| %>
  <%= hidden_field_tag :user_id, friend.id %>
  <%= f.submit delete_message, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-sm button p-0' %>
<% end %>