config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'users', to: 'reloads#user_edit'
  get 'users/password_update', to: 'reloads#user_password_edit'
  resource :users, only: [:edit, :update, :destroy] do
    member do
      post :test_login
      get :password_edit
      patch :password_update
      get :search
      get :favorite_recipes
      get :friends
    end
  end
  resources :users, only: [:show]

  resource :relationships, only: [:create, :update, :destroy]
  resource :bookmarks, only: [:create, :destroy]
  resource :meals, only: [:index, :show]
  resource :menus, only: [:create, :destroy]
  
  get 'recipes/:id/easy_update', to: 'reloads#recipe_show'
  get 'recipes', to: 'reloads#recipe_new'
  get 'recipes/easy_create', to: 'reloads#recipe_new'
  get 'recipes/:id/ingredients', to: 'reloads#ingredients_edit'
  get 'recipes/:id/steps', to: 'reloads#steps_edit'
  resource :recipes, only: [:new, :create] do
    collection do
      post :easy_create
      get :sort
      get :keyword_search
      get :feature_search
    end
  end
  resources :recipes, only: [:show,  :edit, :update, :destroy] do
    member do
      patch :easy_update
      patch :size_update
      patch :publish
      patch :stop_publish
    end
    resource :ingredients, :steps, only: [:edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  with_options presence: true do
    validates :name
    validates :personal_id
    validates :email
    validates :password
  end
  validates :name, presence: true, length: { maximum: 9 }, lt4bytes: true, unless: -> { name.blank? }
  validates :personal_id, presence: true, length: { in: 4..12 }, uniqueness: true,
                          format: { with: /\A[a-zA-Z0-9]+\z/ },  # 半角英数(大文字、小文字、数字)
                          unless: -> { personal_id.blank? }
  before_save { email.downcase! }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    unless: -> { email.blank? }
  has_secure_password
  validates :password, presence: true
  validates :password, length: { in: 4..12 }, format: { with: /\A[a-zA-Z0-9]+\z/ }, # 半角英数(大文字、小文字、数字)
                       unless: -> { password.blank? }

  has_many :recipes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorite_recipes, through: :bookmarks, source: :recipe
  has_many :meals, dependent: :destroy
  # 友だち
  has_many :relationships, dependent: :destroy
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'friend_id', dependent: :destroy,
                                      inverse_of: 'user'
  has_many :friends, through: :relationships, source: :friend
  has_many :requesting_relationships, -> { requesting }, class_name: 'Relationship', inverse_of: 'user'
  has_many :requesting_friends, through: :requesting_relationships, source: :friend
  has_many :receiving_relationships, -> { receiving }, class_name: 'Relationship', inverse_of: 'user'
  has_many :receiving_friends, through: :receiving_relationships, source: :friend
  has_many :approved_relationships, -> { approved }, class_name: 'Relationship', inverse_of: 'user'
  has_many :approved_friends, through: :approved_relationships, source: :friend

  def self.safe_update(user, user_params)
    valid = !!user.authenticate(user_params[:password])
    User.transaction do
      user.assign_attributes(user_params.except(:remove_img))
      user.remove_image! if user_params[:remove_img] == '1'
      valid &= user.save
      raise ActiveRecord::Rollback unless valid
    end
    valid
  end

  def self.safe_password_update(user, password_params)
    valid = !!user.authenticate(password_params[:current_password])
    User.transaction do
      valid &= user.update(password_params.except(:current_password))
      raise ActiveRecord::Rollback unless valid
    end
    valid
  end

  def self.test_user
    random = SecureRandom.hex(5)
    User.create(name: 'テスト太郎', personal_id: random, email: "#{random}@example.com", password: 'testpass')
  end

  def create_default_friends
      friend = User.find(1)
      relationships.find_or_create_by(friend_id: 1, status: 'approved')
      friend.relationships.find_or_create_by(friend_id: id, status: 'approved')
  end

  def friend_request(friend)
    return if self == friend

    relationships.find_or_create_by(friend_id: friend.id)
    relationship = friend.relationships.find_or_create_by(friend_id: id)
    relationship.update(status: 'receiving')
  end

  def friend_approve(friend)
    own_rel = relationships.find_by(friend_id: friend.id)
    own_rel&.update(status: 'approved')
    friend_rel = friend.relationships.find_by(friend_id: id)
    friend_rel&.update(status: 'approved')
  end

  def friend_delete(friend)
    own_rel = relationships.find_by(friend_id: friend.id)
    own_rel&.destroy
    friend_rel = friend.relationships.find_by(friend_id: id)
    friend_rel&.destroy
  end

  def bookmark(recipe)
    bookmarks.find_or_create_by(recipe_id: recipe.id)
  end

  def unbookmark(recipe)
    bookmark = bookmarks.find_by(recipe_id: recipe.id)
    bookmark&.destroy
  end

  def accessable_recipes
    recipes = approved_friends.each_with_object([]) do |friend, array|
      array << friend.recipes.published
    end
    recipes << self.recipes
    recipes.flatten!
    id_list = recipes.pluck(:id)
    Recipe.where(id: id_list)
  end

  # ユーザー検索
  def self.search(search)
    user = User.find_by(personal_id: search)
    user.presence || ''
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, except: %i[new create test_login]
  before_action :prepare_search, except: %i[new create test_login]
  before_action :prepare_meals, except: %i[new create test_login]
  before_action :set_current_user, except: %i[show new create test_login]

  def show
    accessable_user_check
    recipes = @user == current_user ? @user.recipes.recent : @user.recipes.recent.published
    @recipes = recipes.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)
    @user.personal_id = SecureRandom.hex(5)
    if @user.save
      (0..6).each { |index| @user.meals.create(day_of_week: index) }
      login(@user.email, @user.password)
      flash[:success] = '登録しました'
      redirect_to root_url
    else
      render :new
    end
  end

  # def test_login
  #   @user = User.test_user
  #   (0..6).each { |index| @user.meals.create(day_of_week: index) }
  #   @user.create_default_friends
  #   login(@user.email, @user.password)
  #   flash[:success] = 'テストログインしました'
  #   redirect_to root_url
  # end

  def edit; end

  def update
    if User.safe_update(@user, user_params)
      flash[:success] = 'プロフィールが更新されました'
      redirect_to @user
    else
      @user.errors.add(:base, 'パスワードが間違っています') if @user.errors.blank?
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'アカウントが削除されました'
    redirect_to root_url
  end

  def password_edit; end

  def password_update
    if User.safe_password_update(@user, password_params)
      flash[:success] = 'パスワードが更新されました'
      redirect_to @user
    else
      @user.errors.add(:base, '現在のパスワードが間違っています') if @user.errors.blank?
      render :password_edit
    end
  end

  def friends; end

  def search
    @result_user = User.search(params[:search]) unless params[:search] == ''
    render :friends
  end

  def favorite_recipes
    recipes = @user.favorite_recipes.recent & @user.accessable_recipes.recent
    @recipes = Kaminari.paginate_array(recipes).page(params[:page])
  end

  private

  def new_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_params
    params.require(:user).permit(:name, :personal_id, :email, :image, :remove_img, :password, :password_confirmation)
  end

  def password_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end

  def set_current_user
    @user = current_user
  end

  def accessable_user_check
    @user = User.find(params[:id])
    redirect_to root_url unless @user == current_user || current_user.approved_friends.include?(@user)
  end
end

app/views/users/_search_results.html.erb
<div class="row m-0 mb-2">
  <% if user.kind_of?(User) %>
    <div class="col-8 offset-2 col-md-4 offset-md-4">
      <%= image_tag(user.image.to_s, alt: user.name, class: 'rounded-pill') %>
      <div class="d-flex justify-content-center">
        <h1 class="mt-2 mb-0"><%= user.name %></h1>
      </div>
      <div class="d-flex justify-content-center">
        <%= render 'relationships/add_friend_button', user: user %>
      </div>
    </div>
  <% else %>
    <h3>該当するユーザーが見つかりませんでした。</h3>
  <% end %>
</div>

app/views/users/draft_articles.html.erb
<%= render 'layouts/second_navbar' %>

<h4>下書き（非公開の記事）</h4>
<%= render 'articles/articles', articles: @draft_articles %>

app/views/users/edit.html.erb
<% content_for(:html_title) { "プロフィール編集 | Wagakon" } %>
<% breadcrumb :user_edit %>
<%= render "layouts/breadcrumbs" %>
<%= render "layouts/side_bar" do %>
  <div class="px-2">
    <h2>プロフィール編集</h2>
    <%= form_with(url: users_path, model: @user, method: :patch, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: @user %>
      <div class="form-row mt-4">
        <div class="form-group col-md-6">
          <%= f.label :image, "プロフィール画像" %><br>
          <div class="img-square">
            <%= image_tag(@user.image.to_s, alt: @user.name, id: :img_prev) %>
          </div>
          <div class="form-check mb-2">
            <%= f.check_box :remove_img, class: "form-check-input", type: "checkbox", checked_value: "1", unchecked_value: "0", id: "defaultCheck1" %>
            <%= f.label :remove_img, "画像を削除する", class: "form-check-label", for: "defaultCheck1" %>
          </div>          
          <%= f.file_field :image, class: "image", id: "book_img" %>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name, 'ニックネーム' %>
            <%= f.text_field :name, required: :true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :personal_id, 'ID' %>
            <%= f.text_field :personal_id, required: :true, placeholder: "4〜12文字・半角英数", class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, required: :true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, '現在のパスワード' %>
            <%= f.password_field :password, required: :true, class: 'form-control' %>
          </div>
          <p><%= link_to 'パスワードを変更する', password_edit_users_path, class: "font-orange" %></p>
        </div>
        <div class="col-md-4 offset-md-4">
          <%= f.submit '更新', class: 'btn submit-btn btn-block' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/favorite_articles.html.erb
<%= render 'layouts/second_navbar' %>

<h4>ブックマークした記事</h4>
<%= render 'articles/articles', articles: @favorite_articles %>

app/views/users/favorite_recipes.html.erb
<% content_for(:html_title) { "#{@user.name}さんのお気に入りレシピ | Wagakon" } %>
<% breadcrumb :favorite_recipes %>
<%= render "layouts/breadcrumbs" %>
<%= render "layouts/side_bar" do %>    
  <h2 class="ml-2 mb-4">お気に入りのレシピ</h2>
  <%= render 'recipes/index', recipes: @recipes %>
<% end %>

app/views/users/friends.html.erb
<% content_for(:html_title) { "#{@user.name}さんの友だち | Wagakon" } %>
<% breadcrumb :friends %>
<%= render "layouts/breadcrumbs" %>
<%= render "layouts/side_bar" do %>    
  <% if @user.approved_friends.present? %>
    <div class="bg-gray p-2 p-md-3 pb-2 mb-3 mx-2">
      <h2 class="px-2 pt-2"><i class="far fa-user"></i> 友だち</h2>
      <div class="row m-0">
        <% @user.approved_friends.each do |friend| %>
          <div class="col-4 col-md-3 px-2 my-0 mt-2">
            <%= image_tag(friend.image.to_s, alt: friend.name, class: 'rounded-pill') %>
            <div class="d-flex justify-content-center">
              <h3 class="mt-2 mb-0"><%= link_to friend.name, user_path(friend), class: "font-orange" %></h3>
            </div>
            <div class="d-flex justify-content-center">
              <%= render 'relationships/delete_friend_button', user: @user, friend: friend, delete_message: "削除" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>  
  <% end %>
  <div class="mb-4">
    <div class="row px-2 mx-0 mb-2">
      <div class="col-md-12 px-0">
        <h2>友達追加++</h2>
        <div class="border-gray mb-3"></div>
        <!--ユーザー検索フォーム-->
        <%= form_with(url: search_users_path, method: :get, local: true) do |f| %>
          <div class="form-row">
            <div class="col-8 col-md-5">
              <%= f.text_field :search, placeholder: '友達のIDで検索', class: 'form-control' %>
            </div>
            <div class="col-4 col-md-3">
              <%= f.submit '検索', class: 'btn submit-btn' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <% if @result_user %>
      <!--検索結果-->
      <%= render 'users/search_results', user: @result_user %>
    <% end %>
  </div>
  <% if @user.receiving_friends.present? %>
    <div class="bg-gray p-2 p-md-3 pb-2 mb-3 mx-2">
      <h2 class="px-2 pt-2"><i class="far fa-arrow-alt-circle-left"></i> 友だちリクエストされているユーザー</h2>
      <div class="row m-0">
        <% @user.receiving_friends.each do |friend| %>
          <div class="col-4 col-md-3 px-2 my-0 mt-2">
            <%= image_tag(friend.image.to_s, alt: friend.name, class: 'rounded-pill') %>
            <div class="d-flex justify-content-center">
              <h3 class="mt-2 mb-0"><%= friend.name %></h3>
            </div>
            <div class="row d-flex justify-content-center m-0">
              <%= render 'relationships/approve_friend_button', user: @user, friend: friend %>
              <%= render 'relationships/delete_friend_button', user: @user, friend: friend, delete_message: "拒否" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @user.requesting_friends.present? %>
    <div class="bg-gray p-2 p-md-3 pb-2 mb-3 mx-2">
      <h2 class="px-2 pt-2"><i class="far fa-arrow-alt-circle-right"></i> 友だちリクエスト中のユーザー</h2>
      <div class="row m-0">
        <% @user.requesting_friends.each do |friend| %>
          <div class="col-4 col-md-3 px-2 my-0 mt-2">
            <%= image_tag(friend.image.to_s, alt: friend.name, class: 'rounded-pill') %>
            <div class="d-flex justify-content-center">
              <h3 class="mt-2 mb-0"><%= friend.name %></h3>
            </div>
            <div class="d-flex justify-content-center">
              <%= render 'relationships/delete_friend_button', user: @user, friend: friend, delete_message: "取り消し"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<% content_for(:html_title) { "新規会員登録 | Wagakon" } %>
<div class="p-2">
  <div class="text-center">
    <h1>新規会員登録</h1>
  </div>
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= form_with(url: signup_path, model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: @user %>
        <div class="form-group">
          <%= f.label :name, 'ニックネーム' %>
          <%= f.text_field :name, required: :true, placeholder: "例：わがこん太郎", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, required: :true, placeholder: "例：wagakon@example.com", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, required: :true, placeholder: "4〜12文字・半角英数", class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, required: :true, placeholder: "もう一度入力してください", class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn submit-btn btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/password_edit.html.erb
<% content_for(:html_title) { "パスワード編集 | Wagakon" } %>
<% breadcrumb :password_edit %>
<%= render "layouts/breadcrumbs" %>
<%= render "layouts/side_bar" do %>
  <div class="p-2">
    <div class="text-center">
      <h2>パスワード変更</h2>
    </div>
    <%= render 'layouts/error_messages', model: @user %>
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <%= form_with(url: password_update_users_path, model: @user, method: :patch, local: true) do |f| %>
          <div class="form-group">
            <%= f.label :current_password, '現在のパスワード' %>
            <%= f.password_field :current_password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, '新しいパスワード' %>
            <%= f.password_field :password, placeholder: "4〜12文字・半角英数", class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.password_field :password_confirmation, placeholder: "もう一度入力してください", class: 'form-control' %>
          </div>
          <%= f.submit '更新', class: 'btn submit-btn btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% content_for(:html_title) { "#{@user.name}さんのマイページ | Wagakon" } %>
<% current_user == @user ? (breadcrumb :mypage, @user) : (breadcrumb :user, @user) %>
<%= render "layouts/breadcrumbs" %>
<%= render "layouts/side_bar" do %>    
  <div class="bg-gray p-3 mx-2 my-0">
    <div class="row mx-2 mt-4">
      <div class="col-4 col-md-4 px-0 px-md-2">
        <%= image_tag(@user.image.to_s, alt: @user.name, class: 'rounded-pill') %>
      </div>
      <div class="col-8 col-md-8 d-flex">
        <div class="align-self-center">
          <h1 class="d-inline"><%= @user.name %></h1>
          <% if current_user == @user %>
            <h3 class="d-inline">(ID: <%= @user.personal_id %>)</h3>
            <div class="mt-2 mx-1">
              <!--編集、削除ボタン-->
              <%= link_to "編集", edit_users_path, class: 'button pr-2 border-right' %>
              <%= link_to "アカウント削除", users_path, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'button' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 d-flex justify-content-end">
        <% if current_user == @user %>
          <h3><%= link_to ">>友だち", friends_users_path, class: 'font-orange align-self-end' %></h3>
        <% else %>
          <h3>&nbsp;</h3>
        <% end %>  
      </div>
    </div>
  </div>
  <!--投稿レシピ一覧-->
  <h2 class="my-4 mx-2">作成したレシピ</h2>
  <div>
    <%= render 'recipes/index', recipes: @recipes %>
  </div>
<% end %>