config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'users', to: 'reloads#user_edit'
  get 'users/password_update', to: 'reloads#user_password_edit'
  resource :users, only: [:edit, :update, :destroy] do
    member do
      post :test_login
      get :password_edit
      patch :password_update
      get :search
      get :favorite_recipes
      get :friends
    end
  end
  resources :users, only: [:show]

  resource :relationships, only: [:create, :update, :destroy]
  resource :bookmarks, only: [:create, :destroy]
  resource :meals, only: [:index, :show]
  resource :menus, only: [:create, :destroy]
  
  get 'recipes/:id/easy_update', to: 'reloads#recipe_show'
  get 'recipes', to: 'reloads#recipe_new'
  get 'recipes/easy_create', to: 'reloads#recipe_new'
  get 'recipes/:id/ingredients', to: 'reloads#ingredients_edit'
  get 'recipes/:id/steps', to: 'reloads#steps_edit'
  resource :recipes, only: [:new, :create] do
    collection do
      post :easy_create
      get :sort
      get :keyword_search
      get :feature_search
    end
  end
  resources :recipes, only: [:show,  :edit, :update, :destroy] do
    member do
      patch :easy_update
      patch :size_update
      patch :publish
      patch :stop_publish
    end
    resource :ingredients, :steps, only: [:edit, :update]
  end
end

app/views/layouts/_breadcrumbs.html.erb
<div class="mb-2 mb-md-3 px-2">
  <%= breadcrumbs separator: "&nbsp;&nbsp;&gt;&nbsp;&nbsp;" %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="error-messages">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="attention attention-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="border-top">
  <!--<div class="d-flex justify-content-center">-->
    <p>&copy;&nbsp;2021&nbsp;WagaKon</p>
  <!--</div>-->
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand px-0 py-0 py-md-3 m-0 navbar-light">
    <a class="navbar-brand" href="/">WagaKon</a>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <!--ログイン済み-->
        <% if logged_in? %>
          <li class="nav-item nav-icon">
            <%= link_to favorite_recipes_users_path, class: 'nav-link p-0 ml-3 ml-md-4' do %>
              <i class="fas fa-heart"></i>
            <% end %>
          </li>
          <li class="nav-item nav-icon">
            <%= link_to new_recipes_path, class: 'nav-link p-0 ml-3 ml-md-4' do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </li>
          <li>
            <!--マイページ-->
            <div class="dropdown">
              <%= button_tag type: "button", class: "nav-item nav-icon nav-link p-0 ml-3 ml-md-4", id: "dropdownMenuButton", 'data-toggle': :dropdown, 'aria-haspopup': :true, 'aria-expanded': :false do %>
                <i class="far fa-user-circle"></i>
              <% end %>
              <div class="dropdown-menu dropdown-menu-right py-2" aria-labelledby="dropdownMenuButton">
                <%= link_to user_path(current_user), class: 'dropdown-item font-orange px-4 py-2' do %>
                  <div class="">
                    <i class="fas fa-user-circle"></i><p class="d-inline"> マイページ</p>
                    <div class="mt-1">
                      <h2 class="d-inline"><%= current_user.name %></h2><h4 class="d-inline">さん</h4>
                    </div>
                  </div>
                <% end %>
                <div class="dropdown-divider my-2"></div>
                <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item px-4 py-2' %>
              </div>
            </div>  
          </li>
          <div class="d-md-none">
            <li>
              <!--献立List-->
              <div class="dropdown">
                <%= button_tag type: "button", class: "nav-item nav-icon nav-link p-0 ml-3 ml-md-4", id: "dropdownMealButton", 'data-toggle': :dropdown, 'aria-haspopup': :true, 'aria-expanded': :false do %>
                  <i class="fas fa-utensils"></i>
                <% end %>
                <div class="dropdown-menu dropdown-menu-right py-2" aria-labelledby="dropdownMealButton">
                  <div class="dropdown-item px-3">
                    <%= render 'meals/index', recipes: @recipes %>
                  </div>
                </div>
              </div>  
            </li>
          </div>
        <!--ログインなし-->
        <% else %>
          <li class="nav-item"><%= link_to '新規会員登録', signup_path, class: 'nav-link p-0' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link p-0 pl-3' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_side_bar.html.erb
<div class="row mx-0">
  <!--レシピ検索フォーム-->
  <%= render 'recipes/search', keyword: @search_keyword, feature: @search_feature, keyword_submit: @k_submit, feature_submit: @f_submit %>
  <div class="col-md-7 px-0 px-md-2">
    <%= yield %>
  </div>
  <!--献立一覧-->
  <div class="col-md-2 p-0">
    <div class="d-none d-md-block">
      <%= render 'meals/index', recipes: @recipes %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for?(:html_title) ? yield(:html_title) : "WagaKon" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="wrapper">
      <div class="container-fluid px-3">
        <div class="row">
          <div class="col-xl-10 offset-xl-1">
            <%= render 'layouts/navbar' %>
          </div>
        </div>
      </div>
      <div class="border-bottom"></div>
      <div class="container-fluid pt-2 pt-md-3 pb-4 px-2 main">
        <div class="row">
          <div class="col-xl-10 offset-xl-1">
            <%= render 'layouts/flash_messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
      <div>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>